image: ubuntu:20.04

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r book/web/. public/
    - cp -r images/ public/
    - sed -i 's|../../images/|images/|g' public/*.html
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    refs:
      - master
    changes:
      - book/web/*
      - images/*
      - .gitlab-ci.yml

